### ISSUE TITLE
Create new migration by CLI

### ISSUE THREAD

**Issue by alexeymarunin** [lukeed/ley#2]
Is there the way to create new migration (or migration skeleton, with empty `up` and `down` methods) by CLI command?

For example

```bash
ley generate --prefix-timestamp add-users-table
```
will create file `1581760315-add-users-table.js`

**Comment by lukeed** [comment]
Hey :) Maybe haha. Certainly wouldn't add it to the programmatic API. I'm just afraid that adding it to the CLI is kinda useless since it's such a simple file structure, and even a generalized stub would likely need user-tweaking

```js
exports.up = async client => {
  //
}

exports.down = async client => {
  //
}
```

In the meantime, you can certainly do this:

```sh
$ touch "$(date +%s)-create-users.js"
#=> 1581785004-create-users.js
```

If `ley` _were_ to add this, it'd look something like:

```sh
$ ley new create-users --timestamp
```
